### ISSUE TITLE
Sync command wont run as task

### ISSUE THREAD

**Issue by RWienemann** [rvanbekkum/vsc-xliff-sync#112]
I tried to create a task to run the Synchronize Translation Units (after the translations are extracted) in VS Code. The command does not seem to get exceuted, though. I added the following to .vscode/tasks.json
`  {
            "label": "sync xliff",
            "command": "${command:xliffSync.synchronizeSources}",
        }
`
`xliffSync.createNewTargetFiles` does work. Am I missing an argument or setting for this to work?

**Comment by rvanbekkum** [comment]
I also could not get this to work as a VSCode task. Unfortunately, I cannot tell you why either.

A bit off-topic, but also related, I have written a(n) (AL) code analyzer rule that can detect if the translation files are in sync and otherwise raise a warning or error when they are not. It is not publicly available though; we are using it in our company at the moment.

**Comment by rvanbekkum** [comment]
Hi @RWienemann,

It's been quite some time since you have reported this issue. Like I said then, I was not able to get a post-build task after an AL build to work (in general).

Now [FlorianNoeverGOB](https://github.com/FlorianNoeverGOB) has made a pull request which adds a new  `xliffSync.buildWithTranslations` command (Pull Request [#122](https://github.com/rvanbekkum/vsc-xliff-sync/pull/122))
It will be available in the next update soon.

This seems like this will most likely also be a solution for what you would like to achieve.
Could you check and let us know?

**Comment by rvanbekkum** [comment]
Release 1.5.0 was released yesterday. I think it should be of good help.
If you have any further questions, then please let me know. 😊
