### ISSUE TITLE
[Question] Sync upon Package / Build

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#17]
What's the easiest way to integrate syncing all xlf target files automatically upon packaging (AL: Package) / building (Ctrl+F5) an extension (or when the g.xlf file is updated / saved)? Is this something that could be embedded in the XLIFF Sync extension, or should we look into VS Code tasks?

**Comment by rvanbekkum** [comment]
I was also thinking about this, but was not sure where I'd able to hook into. Do you by chance know whether there is an event I could hook into?

Otherwise this will need some further investigation.
Also a thing _might_ need to be taken into account is that the .g.xlf file is updated during packaging/building/compiling.

**Comment by fvet** [comment]
> Do you by chance know whether there is an event I could hook into?

You'll have to ask another VS Code expert I'm afraid ;)

**Comment by rvanbekkum** [comment]
I think the best would be to use a task for this purpose. Also, I could not find another way to hook into the AL build.
From what I understood, you should be able to 'override' what happens when a build is started (see also [this blog](https://navbitsbytes.com/2017/10/14/al-extensions-build-without-deploying-using-visual-studio-code-tasks/)), but for some reason I couldn't get this to work, it would always run the default build steps.

Did you happen to get this working?

**Comment by rvanbekkum** [comment]
Closing this issue for now as it looks like this is something that should not be solved inside this extension.
