### ISSUE TITLE
XLIFF: Create New Target File(s) - Typing in language tag manually

### ISSUE THREAD

**Issue by pmoison** [rvanbekkum/vsc-xliff-sync#26]
Configuration   :
- Multi-root workspaces
Symptoms :
- No error, no file generated

**Comment by rvanbekkum** [comment]
Could you tell me when the command does not work for you?
Just tested this in a multi-root workspace I set up earlier, but I don't run into any issues.

**Comment by pmoison** [comment]
Was user experience fault from my part (rapid keyboad maniac!). Was typing from keyboard the target language and Enter without moving to rhe list, checking the checkbox, and then Enter... 
Could be fine to autovalidate the target language if unique.

**Comment by rvanbekkum** [comment]
I see. I will check if I can change the command so that you can also just type in the target language tag without _needing_ to select one (or more) from the pre-defined list.

**Comment by rvanbekkum** [comment]
It appears that there is a limitation when the `showQuickPick` function from the VSCode API is used with `canPickMany`=**true**: pressing the _Enter_ key will not select the active item, but instead close the menu. With `canPickMany`=**false**, pressing the _Enter_ key _does_ select the active item.

@pmoison Would something like this work for you?
- I will change the command so that by default you will only get to select a single target language.
- Accordingly, I will add two new options:
  - Select multiple... (will let you select multiple files from a list)
  - Enter custom... (will allow you to enter a custom tag, if it is not in the list)

![new-files](https://user-images.githubusercontent.com/7383241/67149000-58cf8a00-f2a6-11e9-9b31-d0a465034e3f.gif)

If you have some ideas/suggestions, please feel free to share!

**Comment by pmoison** [comment]
That sounds great !

**Comment by rvanbekkum** [comment]
This change is shipped in version 0.3.1.
