### ISSUE TITLE
baseFile in multi-project / folder workspaces

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#34]
Our current workspace setup is composed of various folders/projects (one per dependend extension). Each project/folder has its own .vscode folder with a separate settings.json file. Where possible, we like to use a general settings.json file that does not contain differences with the other projects / folders.

Currently, each settings.json files contains one variable setting "xliffSync.baseFile": "extension name.g.xlf". Would be nice if we could replace this with "xliffSync.baseFile": "***.g.xlf**" instead, so we could reuse the settings.json it across different extensions. (Given the condition that there's normally one only g.xlf file per project / folder)

**Comment by rvanbekkum** [comment]
Dear @fvet,
Thank you for reporting your issue. This is indeed a good idea. Currently we are also updating this setting for each project, but it would indeed be better if we can have it the same for each project.

After looking into this, I noticed you can already do this, but then you will need to add the following setting:
```json
"xliffSync.baseFile": ".g.xlf"
```
This is because the function `getXliffSourceFile` uses `uri.fsPath.indexOf(baseFile) >= 0` to retrieve the URI of the base file (i.e., checks if the file path _contains_ the `xliffSync.baseFile` setting value).

I think I will leave it this way, but maybe I can change the **default** value of this setting to become `"xliffSync.baseFile": ".g.xlf"`.
That way, you won't even have to include the setting in your `settings.json` anymore and it will just search for a file with `.g.xlf` in the filename.
What do you think about this?

**Comment by fvet** [comment]
Hey Rob,

Hadn't tried with that setting yet. I've updated all settings to the .g.xlf value, would be nice though if it could be the default value ;)

**Comment by rvanbekkum** [comment]
This change is now included in version 0.3.4.
