### ISSUE TITLE
uft-8 > UFT-8?

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#35]
When using 'Synchronize Translation Units', I often get a delta on the target translation xlf files, without any translation being changed.

![image](https://user-images.githubusercontent.com/25268332/70986908-2633e900-20bf-11ea-8ce8-25f557adb050.png)

The g.xlf and all target translation xlfs contain encoding 'utf-8'. After synching, this is updated by xliff sync to 'UTF-8', resulting in an unnessary commit.

**Comment by rvanbekkum** [comment]
Thank you for filing this issue.

Having the encoding attribute be capitalized `UTF-8` is actually deliberate (and it's also something taken from the VSCode extension that XLIFF Sync is based on, which I decided not to change, deliberately).

The reasons for this can be found here: https://stackoverflow.com/a/3252028

> The XML specification, and unicode.org are consistent about capitalizing UTF-8. 

> additionally, Googling `charset utf-8 uppercase|lowercase bug|solved` turns up quite a number of bug rapports that were solved/circumvented by using uppercase `UTF-8` while I found no rapports (within one evening of googling this subject) where a problem could be solved changing uppercase to lowercase.

While the XML specification uses capitalized UTF-8, one could call it the _de-facto_ standard for declaring the XML encoding. Even though most XML processors will work with both upper-case and lower-case, I chose to have the outputted documents be consistent with the XML specification.

Also, as a sidenote, I create new files with the command `XLIFF: Create New Target File(s)`, so that new files follow this from the start.

Please let me know what you think.

**Comment by fvet** [comment]
Agree with the argumentatiotn, I'll keep an eye on it and try to fix if it would occur again.
