### ISSUE TITLE
issue with Parse From Developer Node 

### ISSUE THREAD

**Issue by GregoryAA** [rvanbekkum/vsc-xliff-sync#43]
Hello Rob,

Set in extension setup Parse From Developer Node  =true
1) Add new label
![image](https://user-images.githubusercontent.com/45356755/79959619-048fa780-848d-11ea-85ad-b8a460ee0535.png)
2) Build app with Ctrl+Shift+B
3) Synchronize Translation Unit
![image](https://user-images.githubusercontent.com/45356755/79959859-50dae780-848d-11ea-89ac-e4f7b52de387.png)
4) Add developer comment and build app
![image](https://user-images.githubusercontent.com/45356755/79959926-6c45f280-848d-11ea-845f-9d81612fe19a.png)
5) Synchronize Translation Unit again
6) No changes in translation
![image](https://user-images.githubusercontent.com/45356755/79960026-90a1cf00-848d-11ea-927e-90ff5d28b0e9.png)
7) Delete target and re-sync 
8) All works as expected 
![image](https://user-images.githubusercontent.com/45356755/79960136-b929c900-848d-11ea-980e-ad5bab1f144f.png)

The same situation if developer decide to  change translation in comment 
![image](https://user-images.githubusercontent.com/45356755/79960507-25a4c800-848e-11ea-86c2-6f63cf57b33a.png)
rebuild app and re-sync
![image](https://user-images.githubusercontent.com/45356755/79960645-4ec55880-848e-11ea-9f1a-2aaff1f26371.png)

Also could you provide the snippet for create developer comments like in AL Language Tools extension
![image](https://user-images.githubusercontent.com/45356755/79961187-035f7a00-848f-11ea-974f-a28dacf80bf3.png)

-

**Comment by rvanbekkum** [comment]
Dear @GregoryAA,
Thank you for reporting this issue.

To summarize, we have the following three points to address:
1. "Parse from Developer Note" should copy the translation from the Developer note also in case that a trans-unit _already_ exists with target state="needs-translation". This sounds logical, I'll look into it.
2. "Parse from Developer Note" is currently not copying a new translation from the Developer note if a translation already exists. This was actually intentional, but I can also see why you'd want to have the translation always updated from the Developer note (if it exists). Perhaps I could add an option, like `parseFromDeveloperNoteOverride` that will toggle this behaviour. What do you think? If you have other ideas, please share! :)
3. This would be an AL-specific feature, but I think I'd could add this specific feature. Can you share some ideas of how you'd like this snippet to work?

**Comment by GregoryAA** [comment]
Hello Rob,

2. Maybe you could add new action "Update Translation from Dev. node" in the context menu under Synchronize Translation Unit?   It seems to me that such an opportunity should always be at hand with the developer. 
![image](https://user-images.githubusercontent.com/45356755/80347165-9d029f00-8874-11ea-9848-e5584cb2e6e0.png)
3. 
- user enters text tcommetwithtranslation
- selects a snippet from the context menu
![image](https://user-images.githubusercontent.com/45356755/80348063-e7d0e680-8875-11ea-8fef-ca4c363acced.png)

-VS code inserts text:  comment = 'LanguageCode=YourLanguageText'
![image](https://user-images.githubusercontent.com/45356755/80348097-f28b7b80-8875-11ea-894e-efc48341103f.png)
- after inserting the snippet, the LanguageCode area becomes active, where the user enters, for example nl-NL and then press TAB, the area YourLanguageText is activated and user enters the translation.

also maybe you can add another snippets for label, tooltip, caption.

tLabelwithComment
LabelName: Label 'EnglishText', comment = 'LanguageCode=YourLanguageText';

tTolTipwithComment
ToolTip = 'EnglishText', comment = 'LanguageCode=YourLanguageText';

tCaptionwithComment
Caption = 'EnglishText', comment = 'LanguageCode=YourLanguageText';

Often, programmers work with one language for translation. It would be nice to save the code of this language in the settings. Then using these snippets we could only enter the translation and the language code would be inserted by default

like this:
comment = 'nl-NL=YourLanguageText'

**Comment by rvanbekkum** [comment]
The changes are shipped in version 0.3.8.
Please see the CHANGELOG and the README for the details.
