### ISSUE TITLE
How to deal with labels marked as 'Locked'?

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#8]
**Scenario**

Label variable declaration that does not require translation.

`MySecondLabel: Label 'MySecondLabel', Locked = true;`

Result in g.xlf

![image](https://user-images.githubusercontent.com/25268332/59347934-1ef9e000-8d16-11e9-9963-15ae3dad8524.png)

Result when synching to nl-BE.xlf

![image](https://user-images.githubusercontent.com/25268332/59347976-3f299f00-8d16-11e9-9e0d-c780feb6af81.png)

Issue:
- 'Next Missing Translation' jumps to this tag, whereas it doesn't require translation.
- POEdit show the translation, whereas it doesn't require translation.

![image](https://user-images.githubusercontent.com/25268332/59348018-61bbb800-8d16-11e9-835e-6ca2ec283f51.png)

**Comment by rvanbekkum** [comment]
Hi @fvet,
Good question, I must say that I didn't know for sure either, so I looked into how AL handles the 'Locked' labels. My guess was that AL will just ignore any translations you provide for trans-units with translate="no" and always just uses the source text.
Personally, what I did up until now was just directly copy the translations for these locked labels from POEdit (Ctrl + B), so that they don't show up as missing translations anymore.

I also made a piece of sample code with a label that has `Locked = true` set to verify what happens with translations for locked labels:
```pascal
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        MyLabel: Label 'This is my GENERAL label', Locked = true;
    begin
        Message(MyLabel);
    end;
}
```
Then, what I put it in my nl-NL.xlf (Dutch (Netherlands)) file was a translation for the label, "This is my NLD label":
![example_nl_xliff](https://user-images.githubusercontent.com/7383241/59554229-0dc40400-8fa0-11e9-8c11-11542c94a59f.png)

Then when I have my client set to Dutch, it appears that I am getting the source text:
![output_message](https://user-images.githubusercontent.com/7383241/59554262-c1c58f00-8fa0-11e9-8dd1-242dd9aca623.png)
So, you could safely copy translations for these labels.

But, probably better would be if (1) these trans-units would not be seen as 'missing' translations and (2) POEdit would either offer an option to hide translations with translate="no" (I think the latter enhancement should be requested to the author of POEdit).

I also found a bug with the sync here: If you add the `Locked = true` part to a label later on, then syncing translation files won't update the "translate" property for such labels from "yes" to "no".
I have logged this bug in a separate issue, see #9.

**Comment by rvanbekkum** [comment]
I have addressed this issue by making the following changes:
* While syncing translations there is now a check for the "translate" attribute. If translate="no", then the trans-unit node in the target file(s) won't get a new empty target-node.
* Also, while syncing, if a trans-unit node is found with translate="no" and it has a target-tag (a translation), then it will be deleted from the target file in question.
* The `XLIFF: Check for Missing Translations` now also checks for the translate attribute, and won't count trans-unit nodes with translate="no" as missing anymore.

I can't change anything myself about POEdit showing the nodes with translate="no" as missing translations, but I will see if I can report it to the author as an enhancement suggestion for XLIFF files.
