### ISSUE TITLE
Synchronization changes state to translated for needs-translation elements

### ISSUE THREAD

**Issue by ik3ras** [rvanbekkum/vsc-xliff-sync#95]
Also noticed that it changes state when importing translations from file.
![image](https://user-images.githubusercontent.com/45070842/125076357-7cfd7b00-e0c8-11eb-9f54-b4222b2cadfd.png)

**Comment by rvanbekkum** [comment]
Thanks for filing this issue. I will have a look! 😉

**Comment by rvanbekkum** [comment]
Hi @ik3ras,
Are you experiencing this with the latest version of XLIFF Sync? I know there used to be a bug for a short period of time, but it was resolved with an earlier update: https://github.com/rvanbekkum/vsc-xliff-sync/blob/develop/CHANGELOG.md#110-26-02-2021
Otherwise, could you let me know when you are getting this exactly?
